version: '3'
volumes:
    mongodata:
services:
    db:
        image: mongo
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
    api:
        build: ./api/
        ports:
            - 8081:8080
        links:
            - db
    website:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./website/www/:/usr/share/nginx/html

