version: '3'
volumes:
    mongodata:
services:
    db:
        image: mongo
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017
    api:
        build: ./api/
        environment:
            - LISTA_CORS
            - LISTA_JWT
        ports:
            - 8081:1337
        links:
            - db
        volumes:
            - ./api/src/:/go/src/lista/api/
        command: go run main.go
    website:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./website/www/:/usr/share/nginx/html

